"""empty message

Revision ID: 727f92429a50
Revises: 5b6a620063a9
Create Date: 2019-07-20 21:38:50.590666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '727f92429a50'
down_revision = '5b6a620063a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dht11',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('temperature', sa.String(length=48), nullable=True),
    sa.Column('humidity', sa.String(length=48), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Dht11_humidity'), 'Dht11', ['humidity'], unique=False)
    op.create_index(op.f('ix_Dht11_temperature'), 'Dht11', ['temperature'], unique=False)
    op.create_index(op.f('ix_Dht11_timestamp'), 'Dht11', ['timestamp'], unique=False)
    op.create_table('Gaz',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('gaz', sa.String(length=48), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Gaz_gaz'), 'Gaz', ['gaz'], unique=False)
    op.create_index(op.f('ix_Gaz_timestamp'), 'Gaz', ['timestamp'], unique=False)
    op.drop_index('ix_gaz_gaz', table_name='gaz')
    op.drop_index('ix_gaz_timestamp', table_name='gaz')
    op.drop_table('gaz')
    op.drop_index('ix_dht11_humidity', table_name='dht11')
    op.drop_index('ix_dht11_temperature', table_name='dht11')
    op.drop_index('ix_dht11_timestamp', table_name='dht11')
    op.drop_table('dht11')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dht11',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('temperature', mysql.VARCHAR(length=48), nullable=True),
    sa.Column('humidity', mysql.VARCHAR(length=48), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_dht11_timestamp', 'dht11', ['timestamp'], unique=False)
    op.create_index('ix_dht11_temperature', 'dht11', ['temperature'], unique=False)
    op.create_index('ix_dht11_humidity', 'dht11', ['humidity'], unique=False)
    op.create_table('gaz',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('gaz', mysql.VARCHAR(length=48), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_gaz_timestamp', 'gaz', ['timestamp'], unique=False)
    op.create_index('ix_gaz_gaz', 'gaz', ['gaz'], unique=False)
    op.drop_index(op.f('ix_Gaz_timestamp'), table_name='Gaz')
    op.drop_index(op.f('ix_Gaz_gaz'), table_name='Gaz')
    op.drop_table('Gaz')
    op.drop_index(op.f('ix_Dht11_timestamp'), table_name='Dht11')
    op.drop_index(op.f('ix_Dht11_temperature'), table_name='Dht11')
    op.drop_index(op.f('ix_Dht11_humidity'), table_name='Dht11')
    op.drop_table('Dht11')
    # ### end Alembic commands ###
