"""empty message

Revision ID: 76fecaafae74
Revises: 
Create Date: 2019-07-30 11:49:04.327458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76fecaafae74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firstname'), 'users', ['firstname'], unique=False)
    op.create_index(op.f('ix_users_lastname'), 'users', ['lastname'], unique=False)
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boards_name'), 'boards', ['name'], unique=False)
    op.create_index(op.f('ix_boards_timestamp'), 'boards', ['timestamp'], unique=False)
    op.create_table('Dht11',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.String(length=48), nullable=True),
    sa.Column('humidity', sa.String(length=48), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Dht11_humidity'), 'Dht11', ['humidity'], unique=False)
    op.create_index(op.f('ix_Dht11_temperature'), 'Dht11', ['temperature'], unique=False)
    op.create_index(op.f('ix_Dht11_timestamp'), 'Dht11', ['timestamp'], unique=False)
    op.create_table('Gaz',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('gaz', sa.String(length=48), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Gaz_gaz'), 'Gaz', ['gaz'], unique=False)
    op.create_index(op.f('ix_Gaz_timestamp'), 'Gaz', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Gaz_timestamp'), table_name='Gaz')
    op.drop_index(op.f('ix_Gaz_gaz'), table_name='Gaz')
    op.drop_table('Gaz')
    op.drop_index(op.f('ix_Dht11_timestamp'), table_name='Dht11')
    op.drop_index(op.f('ix_Dht11_temperature'), table_name='Dht11')
    op.drop_index(op.f('ix_Dht11_humidity'), table_name='Dht11')
    op.drop_table('Dht11')
    op.drop_index(op.f('ix_boards_timestamp'), table_name='boards')
    op.drop_index(op.f('ix_boards_name'), table_name='boards')
    op.drop_table('boards')
    op.drop_index(op.f('ix_users_lastname'), table_name='users')
    op.drop_index(op.f('ix_users_firstname'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
