"""empty message

Revision ID: 8a9df4be2bb6
Revises: 
Create Date: 2019-06-17 22:45:40.479770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9df4be2bb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dht11',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('temperature', sa.String(length=48), nullable=True),
    sa.Column('humidity', sa.String(length=48), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dht11_humidity'), 'dht11', ['humidity'], unique=False)
    op.create_index(op.f('ix_dht11_temperature'), 'dht11', ['temperature'], unique=False)
    op.create_index(op.f('ix_dht11_timestamp'), 'dht11', ['timestamp'], unique=False)
    op.create_table('gaz',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('gaz', sa.String(length=48), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gaz_gaz'), 'gaz', ['gaz'], unique=False)
    op.create_index(op.f('ix_gaz_timestamp'), 'gaz', ['timestamp'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firstname'), 'users', ['firstname'], unique=False)
    op.create_index(op.f('ix_users_lastname'), 'users', ['lastname'], unique=False)
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_', sa.String(length=48), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boards_type_'), 'boards', ['type_'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_boards_type_'), table_name='boards')
    op.drop_table('boards')
    op.drop_index(op.f('ix_users_lastname'), table_name='users')
    op.drop_index(op.f('ix_users_firstname'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index(op.f('ix_gaz_timestamp'), table_name='gaz')
    op.drop_index(op.f('ix_gaz_gaz'), table_name='gaz')
    op.drop_table('gaz')
    op.drop_index(op.f('ix_dht11_timestamp'), table_name='dht11')
    op.drop_index(op.f('ix_dht11_temperature'), table_name='dht11')
    op.drop_index(op.f('ix_dht11_humidity'), table_name='dht11')
    op.drop_table('dht11')
    # ### end Alembic commands ###
