"""empty message

Revision ID: ab4cd954a1c1
Revises: 
Create Date: 2019-06-15 19:44:44.472415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4cd954a1c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dht11',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('temperature', sa.SmallInteger(), nullable=True),
    sa.Column('humidity', sa.SmallInteger(), nullable=True),
    sa.Column('record', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dht11_humidity'), 'dht11', ['humidity'], unique=False)
    op.create_index(op.f('ix_dht11_record'), 'dht11', ['record'], unique=False)
    op.create_index(op.f('ix_dht11_temperature'), 'dht11', ['temperature'], unique=False)
    op.create_table('gaz',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('values', sa.String(length=48), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gaz_values'), 'gaz', ['values'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_gaz_values'), table_name='gaz')
    op.drop_table('gaz')
    op.drop_index(op.f('ix_dht11_temperature'), table_name='dht11')
    op.drop_index(op.f('ix_dht11_record'), table_name='dht11')
    op.drop_index(op.f('ix_dht11_humidity'), table_name='dht11')
    op.drop_table('dht11')
    # ### end Alembic commands ###
