"""empty message

Revision ID: dd8a3ce6410d
Revises: 8a9df4be2bb6
Create Date: 2019-07-18 23:39:53.327582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd8a3ce6410d'
down_revision = '8a9df4be2bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_boards_timestamp'), 'boards', ['timestamp'], unique=False)
    op.add_column('users', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'about_me')
    op.drop_index(op.f('ix_boards_timestamp'), table_name='boards')
    op.drop_column('boards', 'timestamp')
    # ### end Alembic commands ###
